/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CuidadosRouteImport } from './routes/cuidados'
import { Route as PranchasIndexRouteImport } from './routes/pranchas/index'
import { Route as PranchasCategoriaRouteImport } from './routes/pranchas/$categoria'
import { Route as PranchasCategoriaIndexRouteImport } from './routes/pranchas/$categoria/index'
import { Route as PranchasCategoriaModeloRouteImport } from './routes/pranchas/$categoria/$modelo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuidadosRoute = CuidadosRouteImport.update({
  id: '/cuidados',
  path: '/cuidados',
  getParentRoute: () => rootRouteImport,
} as any)
const PranchasIndexRoute = PranchasIndexRouteImport.update({
  id: '/pranchas/',
  path: '/pranchas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PranchasCategoriaRoute = PranchasCategoriaRouteImport.update({
  id: '/pranchas/$categoria',
  path: '/pranchas/$categoria',
  getParentRoute: () => rootRouteImport,
} as any)
const PranchasCategoriaIndexRoute = PranchasCategoriaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PranchasCategoriaRoute,
} as any)
const PranchasCategoriaModeloRoute = PranchasCategoriaModeloRouteImport.update({
  id: '/$modelo',
  path: '/$modelo',
  getParentRoute: () => PranchasCategoriaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cuidados': typeof CuidadosRoute
  '/pranchas/$categoria': typeof PranchasCategoriaRouteWithChildren
  '/pranchas/': typeof PranchasIndexRoute
  '/pranchas/$categoria/$modelo': typeof PranchasCategoriaModeloRoute
  '/pranchas/$categoria/': typeof PranchasCategoriaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cuidados': typeof CuidadosRoute
  '/pranchas': typeof PranchasIndexRoute
  '/pranchas/$categoria/$modelo': typeof PranchasCategoriaModeloRoute
  '/pranchas/$categoria': typeof PranchasCategoriaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cuidados': typeof CuidadosRoute
  '/pranchas/$categoria': typeof PranchasCategoriaRouteWithChildren
  '/pranchas/': typeof PranchasIndexRoute
  '/pranchas/$categoria/$modelo': typeof PranchasCategoriaModeloRoute
  '/pranchas/$categoria/': typeof PranchasCategoriaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cuidados'
    | '/pranchas/$categoria'
    | '/pranchas/'
    | '/pranchas/$categoria/$modelo'
    | '/pranchas/$categoria/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cuidados'
    | '/pranchas'
    | '/pranchas/$categoria/$modelo'
    | '/pranchas/$categoria'
  id:
    | '__root__'
    | '/'
    | '/cuidados'
    | '/pranchas/$categoria'
    | '/pranchas/'
    | '/pranchas/$categoria/$modelo'
    | '/pranchas/$categoria/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CuidadosRoute: typeof CuidadosRoute
  PranchasCategoriaRoute: typeof PranchasCategoriaRouteWithChildren
  PranchasIndexRoute: typeof PranchasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuidados': {
      id: '/cuidados'
      path: '/cuidados'
      fullPath: '/cuidados'
      preLoaderRoute: typeof CuidadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pranchas/': {
      id: '/pranchas/'
      path: '/pranchas'
      fullPath: '/pranchas/'
      preLoaderRoute: typeof PranchasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pranchas/$categoria': {
      id: '/pranchas/$categoria'
      path: '/pranchas/$categoria'
      fullPath: '/pranchas/$categoria'
      preLoaderRoute: typeof PranchasCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pranchas/$categoria/': {
      id: '/pranchas/$categoria/'
      path: '/'
      fullPath: '/pranchas/$categoria/'
      preLoaderRoute: typeof PranchasCategoriaIndexRouteImport
      parentRoute: typeof PranchasCategoriaRoute
    }
    '/pranchas/$categoria/$modelo': {
      id: '/pranchas/$categoria/$modelo'
      path: '/$modelo'
      fullPath: '/pranchas/$categoria/$modelo'
      preLoaderRoute: typeof PranchasCategoriaModeloRouteImport
      parentRoute: typeof PranchasCategoriaRoute
    }
  }
}

interface PranchasCategoriaRouteChildren {
  PranchasCategoriaModeloRoute: typeof PranchasCategoriaModeloRoute
  PranchasCategoriaIndexRoute: typeof PranchasCategoriaIndexRoute
}

const PranchasCategoriaRouteChildren: PranchasCategoriaRouteChildren = {
  PranchasCategoriaModeloRoute: PranchasCategoriaModeloRoute,
  PranchasCategoriaIndexRoute: PranchasCategoriaIndexRoute,
}

const PranchasCategoriaRouteWithChildren =
  PranchasCategoriaRoute._addFileChildren(PranchasCategoriaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CuidadosRoute: CuidadosRoute,
  PranchasCategoriaRoute: PranchasCategoriaRouteWithChildren,
  PranchasIndexRoute: PranchasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
